@music = http://localhost:4110/api

###
GET {{music}}/web
###
GET {{music}}/web/2
###
POST {{music}}/web
Content-Type: application/json

{
    "id": 0, 
    "webName": "Cody's web 2", 
    "info": "Lorem", 
    "authorsRoute": ""
}
###